# Generated by Django 5.0.6 on 2024-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name_plural': 'Knowledge'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'verbose_name_plural': 'Portfolio Categories'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='whatido',
            options={'verbose_name_plural': 'What I Do'},
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
