# Generated by Django 5.0.6 on 2024-05-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_blogcategory_options_alter_knowledge_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_de',
            field=models.FileField(blank=True, null=True, upload_to='cvs/de/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_en',
            field=models.FileField(blank=True, null=True, upload_to='cvs/en/'),
        ),
    ]
